hand_description:
  right_arm:
    hand_frame: r_wrist_roll_link
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: r_gripper_r_finger_tip_link
    hand_group_name: r_end_effector
    arm_group_name: right_arm
    hand_database_name: WILLOW_GRIPPER_2010
    hand_joints: [r_gripper_l_finger_joint,r_gripper_r_finger_joint,r_gripper_r_finger_tip_joint,r_gripper_l_finger_tip_joint]
    hand_touch_links: [r_gripper_palm_link,r_gripper_r_finger_tip_link,r_gripper_l_finger_tip_link,r_gripper_l_finger_link,r_gripper_r_finger_link,r_wrist_roll_link]
    hand_fingertip_links: [r_gripper_r_finger_tip_link,r_gripper_l_finger_tip_link]
    hand_approach_direction: [1.0,0.0,0.0]
    arm_joints: [r_shoulder_pan_joint,r_shoulder_lift_joint,r_upper_arm_roll_joint,r_elbow_flex_joint,r_forearm_roll_joint,r_wrist_flex_joint,r_wrist_roll_joint]
  left_arm:
    hand_frame: l_wrist_roll_link
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: l_gripper_r_finger_tip_link
    hand_group_name: l_end_effector
    arm_group_name: left_arm
    hand_database_name: WILLOW_GRIPPER_2010
    hand_joints: [l_gripper_l_finger_joint,l_gripper_r_finger_joint,l_gripper_r_finger_tip_joint,l_gripper_l_finger_tip_joint]
    hand_touch_links: [l_gripper_palm_link,l_gripper_r_finger_tip_link,l_gripper_l_finger_tip_link,l_gripper_l_finger_link,l_gripper_r_finger_link,l_wrist_roll_link]
    hand_fingertip_links: [l_gripper_r_finger_tip_link,l_gripper_l_finger_tip_link]
    hand_approach_direction: [1.0,0.0,0.0]
    arm_joints: [l_shoulder_pan_joint,l_shoulder_lift_joint,l_upper_arm_roll_joint,l_elbow_flex_joint,l_forearm_roll_joint,l_wrist_flex_joint,l_wrist_roll_joint]
