# The name of the wrist frame for the arm in question (the region of interest in the params are relative to this)
string wrist_frame

---

# The resulting cluster of points in the hand
sensor_msgs/PointCloud2 cluster

# Whether the segmentation succeeded or failed
int32 SUCCESS = 0
int32 NO_CLOUD_RECEIVED = 1
int32 TF_ERROR = 2
int32 OTHER_ERROR = 3
int32 result
